/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => InterlinearPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_state = require("@codemirror/state");
var import_view = require("@codemirror/view");
var LANGUAGES = {
  "es": "Spanish",
  "en": "English",
  "fr": "French",
  "de": "German",
  "it": "Italian",
  "pt": "Portuguese",
  "ru": "Russian",
  "ja": "Japanese",
  "zh": "Chinese (Simplified)",
  "ko": "Korean",
  "ar": "Arabic",
  "hi": "Hindi",
  "tr": "Turkish",
  "nl": "Dutch",
  "pl": "Polish",
  "sv": "Swedish",
  "uk": "Ukrainian",
  "ca": "Catalan",
  "eu": "Basque",
  "gl": "Galician"
};
var DEFAULT_SETTINGS = {
  provider: "google_free",
  targetLang: "es",
  apiKey: "",
  ollamaModel: "qwen2.5:0.5b",
  secondaryColor: "#2ea44f",
  secondarySize: "14px",
  isActive: true,
  savedTranslations: {},
  monthlyCharacterLimit: 5e5,
  alertThresholdPercent: 80,
  currentMonthChars: 0,
  lastResetMonth: new Date().toISOString().slice(0, 7),
  dontAskConfirmClear: false
};
var InterlinearPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.translationCache = /* @__PURE__ */ new Map();
    this.requestQueue = [];
    this.isProcessingQueue = false;
    this.ribbonIconEl = null;
    this.statusBarItemEl = null;
    this.saveCacheToDisk = (0, import_obsidian.debounce)(async () => {
      this.settings.savedTranslations = Object.fromEntries(this.translationCache);
      await this.saveData(this.settings);
    }, 5e3, true);
  }
  async onload() {
    await this.loadSettings();
    this.translationCache = new Map(Object.entries(this.settings.savedTranslations || {}));
    this.checkMonthlyReset();
    this.addCommand({
      id: "toggle-translator",
      name: "Toggle Translator On/Off",
      hotkeys: [{ modifiers: ["Alt", "Shift"], key: "t" }],
      callback: () => this.togglePluginStatus()
    });
    this.statusBarItemEl = this.addStatusBarItem();
    this.updateStatusBar();
    this.ribbonIconEl = this.addRibbonIcon("languages", "Interlinear Translator", () => this.togglePluginStatus());
    this.updateRibbonIcon();
    this.registerEditorExtension(this.liveTranslationExtension());
    this.addSettingTab(new InterlinearSettingTab(this.app, this));
  }
  checkMonthlyReset() {
    const currentMonth = new Date().toISOString().slice(0, 7);
    if (this.settings.lastResetMonth !== currentMonth) {
      this.settings.currentMonthChars = 0;
      this.settings.lastResetMonth = currentMonth;
      this.saveSettings();
      new import_obsidian.Notice("\u{1F4C5} New Month: API Usage Counter Reset.");
    }
  }
  async togglePluginStatus() {
    this.settings.isActive = !this.settings.isActive;
    await this.saveSettings();
    this.updateRibbonIcon();
    this.updateStatusBar();
    new import_obsidian.Notice(this.settings.isActive ? `Translator: ON (${this.getProviderName()})` : "Translator: OFF");
    this.app.workspace.updateOptions();
  }
  getProviderName() {
    switch (this.settings.provider) {
      case "google_free":
        return "Free";
      case "google_api":
        return "PRO";
      case "local_ollama":
        return "Local";
    }
  }
  updateStatusBar() {
    if (!this.statusBarItemEl)
      return;
    if (!this.settings.isActive) {
      this.statusBarItemEl.setText("\u{1F515} Translator Off");
      this.statusBarItemEl.style.color = "";
    } else {
      const mode = this.settings.provider;
      let icon = "\u{1F7E2}";
      let color = "#66ff66";
      if (mode === "google_api") {
        icon = "\u26A1";
        color = "#ffcc00";
        const percent = (this.settings.currentMonthChars / this.settings.monthlyCharacterLimit * 100).toFixed(1);
        this.statusBarItemEl.setText(`${icon} PRO (${percent}%)`);
        this.statusBarItemEl.style.color = color;
        return;
      }
      if (mode === "local_ollama") {
        icon = "\u{1F512}";
        color = "#00ffff";
      }
      this.statusBarItemEl.setText(`${icon} ${this.getProviderName()}`);
      this.statusBarItemEl.style.color = color;
    }
  }
  updateRibbonIcon() {
    if (!this.ribbonIconEl)
      return;
    this.settings.isActive ? this.ribbonIconEl.style.opacity = "1" : this.ribbonIconEl.style.opacity = "0.4";
  }
  liveTranslationExtension() {
    return import_state.StateField.define({
      create: () => import_view.Decoration.none,
      update: (decorations, transaction) => {
        if (!this.settings.isActive)
          return import_view.Decoration.none;
        return this.getDecorations(transaction.state.doc);
      },
      provide: (field) => import_view.EditorView.decorations.from(field)
    });
  }
  getDecorations(doc) {
    const builder = new import_state.RangeSetBuilder();
    for (let i = 1; i <= doc.lines; i++) {
      const line = doc.line(i);
      const text = line.text.trim();
      if (text.length < 3 || text.startsWith("```") || text.startsWith("$$"))
        continue;
      const cacheKey = `${text}_${this.settings.targetLang}_${this.settings.provider}`;
      let translatedText = "...";
      let isWaiting = true;
      if (this.translationCache.has(cacheKey)) {
        translatedText = this.translationCache.get(cacheKey) || "";
        isWaiting = false;
      } else {
        if (!this.requestQueue.includes(text))
          this.addToQueue(text);
      }
      builder.add(line.to, line.to, import_view.Decoration.widget({
        widget: new TranslationWidget(translatedText, this.settings, isWaiting),
        side: 1,
        block: true
      }));
    }
    return builder.finish();
  }
  addToQueue(text) {
    if (!this.requestQueue.includes(text)) {
      this.requestQueue.push(text);
      this.processQueue();
    }
  }
  async processQueue() {
    if (this.isProcessingQueue)
      return;
    this.isProcessingQueue = true;
    while (this.requestQueue.length > 0) {
      const textToTranslate = this.requestQueue[0];
      const cacheKey = `${textToTranslate}_${this.settings.targetLang}_${this.settings.provider}`;
      let delay = 800;
      if (this.settings.provider === "google_api")
        delay = 200;
      if (this.settings.provider === "local_ollama")
        delay = 300;
      await sleep(delay);
      if (!this.translationCache.has(cacheKey)) {
        try {
          let result = "";
          if (this.settings.provider === "local_ollama") {
            result = await this.translateLocal(textToTranslate);
          } else if (this.settings.provider === "google_api") {
            result = await this.translateGooglePro(textToTranslate);
          } else {
            result = await this.translateGoogleFree(textToTranslate);
          }
          const esError = result.startsWith("\u26A0\uFE0F") || result.includes("Error") || result.includes("Key");
          if (!esError) {
            this.translationCache.set(cacheKey, result);
            this.saveCacheToDisk();
          }
          try {
            this.app.workspace.updateOptions();
          } catch (e) {
          }
        } catch (error) {
          await sleep(2e3);
        }
      }
      this.requestQueue.shift();
    }
    this.isProcessingQueue = false;
  }
  async translateGoogleFree(text) {
    var _a, _b, _c;
    const url = `https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=${this.settings.targetLang}&dt=t&q=${encodeURIComponent(text)}`;
    const response = await (0, import_obsidian.requestUrl)({ url });
    return ((_c = (_b = (_a = response.json) == null ? void 0 : _a[0]) == null ? void 0 : _b[0]) == null ? void 0 : _c[0]) || "Error";
  }
  async translateGooglePro(text) {
    var _a, _b, _c, _d;
    if (!this.settings.apiKey)
      return "\u26A0\uFE0F Missing API Key";
    const limit = this.settings.monthlyCharacterLimit;
    const current = this.settings.currentMonthChars;
    const threshold = this.settings.alertThresholdPercent / 100 * limit;
    if (current < threshold && current + text.length >= threshold) {
      new import_obsidian.Notice(`\u26A0\uFE0F USAGE ALERT: You have crossed ${this.settings.alertThresholdPercent}% of your monthly quota.`);
    }
    const url = `https://translation.googleapis.com/language/translate/v2?key=${this.settings.apiKey}`;
    const response = await (0, import_obsidian.requestUrl)({
      url,
      method: "POST",
      body: JSON.stringify({ q: text, target: this.settings.targetLang, format: "text" })
    });
    const translated = (_d = (_c = (_b = (_a = response.json) == null ? void 0 : _a.data) == null ? void 0 : _b.translations) == null ? void 0 : _c[0]) == null ? void 0 : _d.translatedText;
    if (translated) {
      this.settings.currentMonthChars += text.length;
      this.updateStatusBar();
      await this.saveData(this.settings);
    }
    return translated || "Error API";
  }
  async translateLocal(text) {
    var _a, _b;
    const systemPrompt = `Translate to ${this.settings.targetLang}. Output ONLY translation.`;
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url: "http://localhost:11434/api/generate",
        method: "POST",
        body: JSON.stringify({
          model: this.settings.ollamaModel,
          system: systemPrompt,
          prompt: text,
          stream: false,
          options: { temperature: 0.1 }
        })
      });
      return ((_b = (_a = response.json) == null ? void 0 : _a.response) == null ? void 0 : _b.trim()) || "Error Local";
    } catch (e) {
      return "\u26A0\uFE0F Open Ollama App";
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.app.workspace.updateOptions();
    this.updateRibbonIcon();
    this.updateStatusBar();
  }
};
var TranslationWidget = class extends import_view.WidgetType {
  constructor(text, settings, isWaiting) {
    super();
    this.text = text;
    this.settings = settings;
    this.isWaiting = isWaiting;
  }
  toDOM(view) {
    const div = document.createElement("div");
    div.className = "interlinear-widget";
    const esError = this.text.startsWith("\u26A0\uFE0F");
    if (this.isWaiting && !this.text) {
      div.innerText = "\u23F3";
      div.style.opacity = "0.5";
    } else {
      const txt = new DOMParser().parseFromString(this.text, "text/html").documentElement.textContent;
      div.innerText = txt || "";
      if (esError) {
        div.style.color = "#ff4444";
        div.style.fontSize = "12px";
      } else {
        div.style.color = this.settings.secondaryColor;
        div.style.fontSize = this.settings.secondarySize;
      }
    }
    return div;
  }
};
var ConfirmModal = class extends import_obsidian.Modal {
  constructor(app, plugin, onSubmit) {
    super(app);
    this.plugin = plugin;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "\u26A0\uFE0F Clear Database?" });
    contentEl.createEl("p", { text: "This will delete all saved translations. This action cannot be undone." });
    const div = contentEl.createDiv();
    const checkbox = div.createEl("input", { type: "checkbox" });
    div.createEl("span", { text: " Don't ask again (Always confirm)" });
    div.style.marginBottom = "20px";
    const buttonContainer = contentEl.createDiv();
    buttonContainer.style.display = "flex";
    buttonContainer.style.gap = "10px";
    buttonContainer.style.justifyContent = "flex-end";
    const btnCancel = buttonContainer.createEl("button", { text: "Cancel" });
    btnCancel.onClickEvent(() => {
      this.close();
    });
    const btnConfirm = buttonContainer.createEl("button", { text: "Yes, Delete" });
    btnConfirm.classList.add("mod-warning");
    btnConfirm.onClickEvent(() => {
      this.onSubmit(true, checkbox.checked);
      this.close();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var InterlinearSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u{1F30D} Interlinear Translator Settings" });
    new import_obsidian.Setting(containerEl).setName("\u{1F5D1}\uFE0F Clear Database").setDesc("Deletes all saved translations to free up space or fix errors.").addButton((button) => button.setButtonText("Clear Memory").setWarning().onClick(async () => {
      if (this.plugin.settings.dontAskConfirmClear) {
        this.clearDatabase();
      } else {
        new ConfirmModal(this.app, this.plugin, (result, dontAsk) => {
          if (result) {
            if (dontAsk) {
              this.plugin.settings.dontAskConfirmClear = true;
              this.plugin.saveSettings();
            }
            this.clearDatabase();
          }
        }).open();
      }
    }));
    new import_obsidian.Setting(containerEl).setName("Translation Mode").addDropdown((d) => d.addOption("google_free", "\u{1F7E2} Basic (Free - Slow)").addOption("google_api", "\u26A1 Pro (API Key - Fast)").addOption("local_ollama", "\u{1F512} Private (Ollama - Local)").setValue(this.plugin.settings.provider).onChange(async (v) => {
      this.plugin.settings.provider = v;
      await this.plugin.saveSettings();
      this.display();
    }));
    if (this.plugin.settings.provider === "google_api") {
      containerEl.createEl("h3", { text: "\u{1F4B0} Cost Control (Pro Mode)" });
      new import_obsidian.Setting(containerEl).setName("\u{1F511} Google API Key").addText((t) => t.setValue(this.plugin.settings.apiKey).onChange(async (v) => {
        this.plugin.settings.apiKey = v;
        await this.plugin.saveSettings();
      }));
      new import_obsidian.Setting(containerEl).setName("\u{1F4CA} Characters Used (Month)").addText((t) => t.setValue(this.plugin.settings.currentMonthChars.toString()).setDisabled(true));
      new import_obsidian.Setting(containerEl).setName("\u{1F514} Usage Warning Threshold (%)").setDesc("Notify me when usage reaches this percentage (0-100).").addText((text) => text.setPlaceholder("80.00").setValue(this.plugin.settings.alertThresholdPercent.toFixed(2)).onChange(async (value) => {
        let num = parseFloat(value);
        if (isNaN(num))
          return;
        if (num < 0)
          num = 0;
        if (num > 100)
          num = 100;
        this.plugin.settings.alertThresholdPercent = num;
        await this.plugin.saveSettings();
      }));
    }
    if (this.plugin.settings.provider === "local_ollama") {
      new import_obsidian.Setting(containerEl).setName("\u{1F916} Ollama Model").addText((t) => t.setValue(this.plugin.settings.ollamaModel).onChange(async (v) => {
        this.plugin.settings.ollamaModel = v;
        await this.plugin.saveSettings();
      }));
    }
    containerEl.createEl("h3", { text: "\u{1F3A8} Appearance" });
    new import_obsidian.Setting(containerEl).setName("Target Language").addDropdown((dropdown) => {
      const sortedLangs = Object.entries(LANGUAGES).sort((a, b) => a[1].localeCompare(b[1]));
      sortedLangs.forEach(([code, name]) => dropdown.addOption(code, name));
      dropdown.setValue(this.plugin.settings.targetLang);
      dropdown.onChange(async (value) => {
        this.plugin.settings.targetLang = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Text Color").addColorPicker((c) => c.setValue(this.plugin.settings.secondaryColor).onChange(async (v) => {
      this.plugin.settings.secondaryColor = v;
      await this.plugin.saveSettings();
    }));
  }
  async clearDatabase() {
    this.plugin.settings.savedTranslations = {};
    this.plugin.translationCache.clear();
    await this.plugin.saveSettings();
    new import_obsidian.Notice("\u2705 Memory cleared successfully.");
    this.plugin.app.workspace.updateOptions();
  }
};
function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
